name: PR_REVIEW_SUBMISSION

on:
  pull_request_review:
    types: [submitted, edited]

jobs:
  post_review_service_url:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.ref }}
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.base.ref }}
          echo "commit id ${{ github.event.pull_request.head.sha }}"
          
          echo "Review State: ${{ github.event.review.state }}"
          echo "Review Body: ${{ github.event.review.body }}"
          echo "Review Changes: ${{ toJson(github.event.changes) }}"

          PR_NUMBER="${{ github.event.pull_request.number }}"
          REVIEW_ID="${{ github.event.review.id }}"
          REVIEWERS="${{ github.event.reviewers }}"
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews/${REVIEW_ID}/comments"
          echo $COMMENT_URL
          echo $REVIEWERS

          # curl --location 'http://192.168.29.33:5000/test_chat'
          response=$(curl --location --request POST 'https://8eab-2001-420-c0e0-1004-00-4ee.ngrok-free.app/onreviewsubmission' \
              --header 'Authorization: Basic c2Ryb2xpYUBjaXNjby5jb206c2Ryb2xpYUBjaXNjby5jb20=' \
              --data-raw $COMMENT_URL)
          echo "on review submission response $response"
